version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "quarkus_db"
      POSTGRES_USER: "quarkus"
      POSTGRES_PASSWORD: "secret"
    ports:
      - 5432:5432
    networks:
      - quarkus_local
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'db@quarkus.com'
      PGADMIN_DEFAULT_PASSWORD: 'quarkus'
    ports:
      - 8083:80
    depends_on:
      - postgres
    networks:
      - quarkus_local
  quarkus_exploration:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      DB_URL: "postgres"
    ports:
      - 8080:8080
    networks:
      - quarkus_local
networks:
  quarkus_local: